language: scala
scala:
- 2.11.8
jdk:
- oraclejdk7
env:
  global:
  - LIB_VERSION=$TRAVIS_BUILD_NUMBER
  -  secure: sxAKLpY1oAgweFHaPMATGJgwD3LxIm4yzcYNMGyQfNEwn9ghc5bAz8Xiyng/oB/bh6pc7P1a7kl1uD+54xwR02EHLju7l84uysVeeGt/IVJPCdfatvEn2JLGEC7JddKol7BAtYK94c5Qn7aUwY2jxvreyeWz8utUr1lHnOAuqdZUv6UODGhzP/reRtRFrP+TOeiFnKIzGpOQRJkXgtpKQER6jbg3FZHGlx0vyNb3Px0X8BOoWpZEGMJEklSndXjFfSndNX4wsyYZF2cNG1fleq3rVuZ/yDgPQ1aKWpEII2OQZS0BAVQBWR5vP9/U/mchAHJnJuiRu3xLlRdDneJZAElAOPwJRsnjPpHbkf3uEGDn2CafPeE3oW6uKvTB+JoX3n1QVQtoFSMEC4L/NTmioM1f2VXtj1KRiSbnAf448L66t+d9ZYHJfmNHJeEC6qOr4VH28WjnbKzqNkQumUV8RVXTzaYkRRdiKj8ZBCR6KQ/+GaIcB4APsc2wgS+OPj/yVZsgmcmH/JDZFfCMNJ/k/EIMSLj12u1svmg/gtv5a5Zpvxwr4lYszOo5J5l/quX/WSE8rYyxMN4RtDDoYq2fEF2WyD6l8P0F9PprAKg05D88qaRk6x4CyFM11CrngO8qGCqmva0PU+A1cmR8G+dDQV6CtiLb0CAClnHBY0xXGcE=
before_script: "./publish/bintray.sh"
script: sbt test +publishSigned
